-- PR 3: RBAC permission catalogue + role defaults seed.
-- Generated from backend/seeds/permissions_seed.py; idempotent re-runs are safe.
INSERT INTO public.permissions VALUES ('personas.read', 'View personas', 'personas', 'Read access to persona records');
INSERT INTO public.permissions VALUES ('personas.write', 'Manage personas', 'personas', 'Create or update personas');
INSERT INTO public.permissions VALUES ('personas.delete', 'Delete personas', 'personas', 'Delete personas');
INSERT INTO public.permissions VALUES ('creatives.read', 'View creatives', 'creatives', 'Read access to creative assets');
INSERT INTO public.permissions VALUES ('creatives.write', 'Manage creatives', 'creatives', 'Create or update creatives');
INSERT INTO public.permissions VALUES ('creatives.generate', 'Generate creatives', 'creatives', 'Trigger AI creative generation');
INSERT INTO public.permissions VALUES ('campaigns.read', 'View campaigns', 'campaigns', 'Read access to campaigns');
INSERT INTO public.permissions VALUES ('campaigns.write', 'Manage campaigns', 'campaigns', 'Create or update campaigns');
INSERT INTO public.permissions VALUES ('campaigns.publish', 'Publish campaigns', 'campaigns', 'Push campaigns live to ad platforms');
INSERT INTO public.permissions VALUES ('campaigns.budget.manage', 'Manage campaign budgets', 'campaigns', 'Edit budget config');
INSERT INTO public.permissions VALUES ('attribution.read', 'View attribution', 'attribution', 'Read attribution reports');
INSERT INTO public.permissions VALUES ('attribution.report.create', 'Create attribution reports', 'attribution', 'Run new attribution analyses');
INSERT INTO public.permissions VALUES ('reports.read', 'View reports', 'reports', 'Read scheduled & ad-hoc reports');
INSERT INTO public.permissions VALUES ('reports.create', 'Create reports', 'reports', 'Build new reports');
INSERT INTO public.permissions VALUES ('reports.export', 'Export reports', 'reports', 'Download report files');
INSERT INTO public.permissions VALUES ('reports.schedule.manage', 'Manage report schedules', 'reports', 'Schedule recurring reports');
INSERT INTO public.permissions VALUES ('imports.upload', 'Upload imports', 'imports', 'Upload CSV / file imports');
INSERT INTO public.permissions VALUES ('team.view', 'View team', 'team', 'List team members');
INSERT INTO public.permissions VALUES ('team.invite', 'Invite team members', 'team', 'Send team invitations');
INSERT INTO public.permissions VALUES ('team.deactivate', 'Deactivate team members', 'team', 'Disable team accounts');
INSERT INTO public.permissions VALUES ('team.role.update', 'Change team roles', 'team', 'Update a member''s role');
INSERT INTO public.permissions VALUES ('clients.view', 'View clients', 'clients', 'List clients');
INSERT INTO public.permissions VALUES ('clients.create', 'Create clients', 'clients', 'Add new clients');
INSERT INTO public.permissions VALUES ('clients.invite_viewer', 'Invite client viewer', 'clients', 'Send portal invitations');
INSERT INTO public.permissions VALUES ('clients.delete', 'Delete clients', 'clients', 'Remove a client');
INSERT INTO public.permissions VALUES ('settings.view', 'View settings', 'settings', 'View agency / account settings');
INSERT INTO public.permissions VALUES ('settings.edit_brand', 'Edit brand settings', 'settings', 'Modify branding');
INSERT INTO public.permissions VALUES ('settings.edit_compliance', 'Edit compliance settings', 'settings', 'Modify compliance config');
INSERT INTO public.permissions VALUES ('settings.permissions.manage', 'Manage agency permissions', 'settings', 'Override permission defaults for this agency');
INSERT INTO public.permissions VALUES ('integrations.view', 'View integrations', 'integrations', 'List connected integrations');
INSERT INTO public.permissions VALUES ('integrations.connect', 'Connect integrations', 'integrations', 'Add new integrations');
INSERT INTO public.permissions VALUES ('integrations.disconnect', 'Disconnect integrations', 'integrations', 'Remove integrations');
INSERT INTO public.permissions VALUES ('audience_export.view', 'View audience exports', 'audience_export', 'List audience exports');
INSERT INTO public.permissions VALUES ('audience_export.create', 'Create audience exports', 'audience_export', 'Push audiences to ad platforms');
INSERT INTO public.permissions VALUES ('portal.access', 'Access client portal', 'portal', 'Read-only client portal access');
INSERT INTO public.permissions VALUES ('notifications.read', 'View notifications', 'notifications', 'List user notifications');
INSERT INTO public.permissions VALUES ('platform.agency.view', 'View agencies', 'platform', 'List all agencies');
INSERT INTO public.permissions VALUES ('platform.agency.create', 'Create agencies', 'platform', 'Provision new agencies');
INSERT INTO public.permissions VALUES ('platform.agency.suspend', 'Suspend agencies', 'platform', 'Suspend an agency');
INSERT INTO public.permissions VALUES ('platform.agency.delete', 'Delete agencies', 'platform', 'Destructive — delete an agency');
INSERT INTO public.permissions VALUES ('platform.agency.invite_admin', 'Invite agency admins', 'platform', 'Send agency-admin invitations');
INSERT INTO public.permissions VALUES ('platform.users.view', 'View platform users', 'platform', 'List platform-tier users');
INSERT INTO public.permissions VALUES ('platform.users.invite', 'Invite platform users', 'platform', 'Send platform-tier invitations');
INSERT INTO public.permissions VALUES ('platform.permissions.manage', 'Manage platform permissions', 'platform', 'Edit role permission defaults');
INSERT INTO public.permissions VALUES ('platform.audit.read', 'Read audit log', 'platform', 'View the cross-tenant audit log');
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'creatives.generate', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'integrations.connect', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.agency.invite_admin', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'team.invite', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.agency.create', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'audience_export.create', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'campaigns.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'personas.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'settings.permissions.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'clients.create', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'integrations.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.audit.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'settings.edit_brand', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'portal.access', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.users.invite', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'reports.schedule.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'reports.export', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.agency.delete', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'team.role.update', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'imports.upload', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'team.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'creatives.write', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'creatives.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'attribution.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.agency.suspend', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.users.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'personas.delete', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'clients.delete', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'clients.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'audience_export.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.agency.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'campaigns.publish', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'personas.write', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'integrations.disconnect', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'team.deactivate', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'platform.permissions.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'reports.create', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'settings.view', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'attribution.report.create', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'campaigns.write', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'clients.invite_viewer', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'campaigns.budget.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'notifications.read', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'settings.edit_compliance', true);
INSERT INTO public.role_permissions VALUES ('platform_super_admin', 'reports.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'creatives.generate', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'integrations.connect', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.agency.invite_admin', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'team.invite', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.agency.create', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'audience_export.create', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'campaigns.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'personas.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'settings.permissions.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'clients.create', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'integrations.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.audit.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'settings.edit_brand', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'portal.access', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.users.invite', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'reports.schedule.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'reports.export', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.agency.delete', false);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'team.role.update', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'imports.upload', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'team.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'creatives.write', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'creatives.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'attribution.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.agency.suspend', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.users.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'personas.delete', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'clients.delete', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'clients.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'audience_export.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.agency.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'campaigns.publish', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'personas.write', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'integrations.disconnect', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'team.deactivate', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'platform.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'reports.create', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'settings.view', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'attribution.report.create', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'campaigns.write', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'clients.invite_viewer', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'campaigns.budget.manage', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'notifications.read', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'settings.edit_compliance', true);
INSERT INTO public.role_permissions VALUES ('platform_admin', 'reports.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'creatives.generate', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'integrations.connect', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.agency.invite_admin', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'team.invite', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.agency.create', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'audience_export.create', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'campaigns.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'personas.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'settings.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'clients.create', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'integrations.view', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.audit.read', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'settings.edit_brand', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'portal.access', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.users.invite', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'reports.schedule.manage', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'reports.export', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.agency.delete', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'team.role.update', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'imports.upload', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'team.view', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'creatives.write', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'creatives.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'attribution.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.agency.suspend', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.users.view', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'personas.delete', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'clients.delete', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'clients.view', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'audience_export.view', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.agency.view', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'campaigns.publish', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'personas.write', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'integrations.disconnect', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'team.deactivate', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'platform.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'reports.create', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'settings.view', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'attribution.report.create', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'campaigns.write', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'clients.invite_viewer', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'campaigns.budget.manage', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'notifications.read', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'settings.edit_compliance', true);
INSERT INTO public.role_permissions VALUES ('agency_admin', 'reports.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'creatives.generate', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'integrations.connect', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.agency.invite_admin', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'team.invite', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.agency.create', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'audience_export.create', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'campaigns.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'personas.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'settings.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'clients.create', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'integrations.view', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.audit.read', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'settings.edit_brand', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'portal.access', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.users.invite', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'reports.schedule.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'reports.export', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.agency.delete', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'team.role.update', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'imports.upload', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'team.view', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'creatives.write', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'creatives.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'attribution.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.agency.suspend', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.users.view', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'personas.delete', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'clients.delete', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'clients.view', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'audience_export.view', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.agency.view', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'campaigns.publish', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'personas.write', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'integrations.disconnect', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'team.deactivate', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'platform.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'reports.create', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'settings.view', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'attribution.report.create', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'campaigns.write', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'clients.invite_viewer', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'campaigns.budget.manage', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'notifications.read', true);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'settings.edit_compliance', false);
INSERT INTO public.role_permissions VALUES ('agency_ops', 'reports.read', true);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'creatives.generate', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'integrations.connect', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.agency.invite_admin', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'team.invite', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.agency.create', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'audience_export.create', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'campaigns.read', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'personas.read', true);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'settings.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'clients.create', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'integrations.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.audit.read', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'settings.edit_brand', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'portal.access', true);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.users.invite', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'reports.schedule.manage', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'reports.export', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.agency.delete', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'team.role.update', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'imports.upload', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'team.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'creatives.write', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'creatives.read', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'attribution.read', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.agency.suspend', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.users.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'personas.delete', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'clients.delete', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'clients.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'audience_export.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.agency.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'campaigns.publish', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'personas.write', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'integrations.disconnect', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'team.deactivate', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'platform.permissions.manage', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'reports.create', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'settings.view', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'attribution.report.create', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'campaigns.write', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'clients.invite_viewer', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'campaigns.budget.manage', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'notifications.read', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'settings.edit_compliance', false);
INSERT INTO public.role_permissions VALUES ('client_viewer', 'reports.read', true);
